# Generated by Django 4.2.1 on 2024-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0003_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
