# Generated by Django 4.2.1 on 2024-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0005_alter_patient_email_alter_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
