# Generated by Django 4.2.1 on 2024-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0007_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_info',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='open_hours',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
