# Generated by Django 4.2.1 on 2024-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0011_dentist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration of the treatment in minutes'),
            preserve_default=False,
        ),
    ]
