# Generated by Django 4.2.1 on 2024-10-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0012_treatment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DentalApp.dentist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='DentalApp.treatment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
