# Generated by Django 4.2.1 on 2024-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0013_appointment_dentist_appointment_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.CharField(blank=True),
        ),
    ]
