# Generated by Django 4.2.1 on 2024-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0014_alter_appointment_end_time_alter_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
    ]
