# Generated by Django 4.2.1 on 2024-10-16 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0016_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
