# Generated by Django 4.2.1 on 2024-10-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0019_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='DentalApp.patient'),
            preserve_default=False,
        ),
    ]
